# Generated by Django 3.2.11 on 2022-01-05 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='name',
            old_name='name',
            new_name='allname',
        ),
    ]
