# Generated by Django 3.2.11 on 2022-01-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_allname_name_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description1', models.TextField(max_length=20)),
                ('description2', models.TextField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
