# Generated by Django 3.2.11 on 2022-01-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20220105_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description2',
        ),
    ]
