# Generated by Django 3.2.11 on 2022-01-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20220105_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='about/')),
                ('image2', models.ImageField(upload_to='about/')),
                ('image3', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
