# Generated by Django 3.2.11 on 2022-01-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_remove_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='pdf')),
                ('image1', models.ImageField(upload_to='about/')),
            ],
        ),
    ]
