# Generated by Django 3.2.11 on 2022-01-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20220113_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='link',
            field=models.URLField(blank=True, max_length=128),
        ),
    ]
