# Generated by Django 3.2.11 on 2022-01-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='link5',
            field=models.CharField(blank=True, max_length=12, verbose_name='Phone'),
        ),
    ]
