# Generated by Django 3.2.11 on 2022-01-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_alter_social_link5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='link5',
            field=models.URLField(blank=True, verbose_name='Phone'),
        ),
    ]
